name: Flask Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Docker Image
        # Image ka naya naam rakh diya hai
        run: docker build -t docker-flask-app .

      - name: Run Tests in Docker Container
        # Yahan hum Dockerfile ke default CMD ko override kar rahe hain
        # Taaki server start na ho, balki sirf tests run hon
        run: docker run docker-flask-app uv run pytest