name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Code ko repository se uthana
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Docker image build karna
      - name: Build Docker Image
        run: docker build -t docker-python-app .

      # Step 3: Container ke andar tests run karna
      - name: Run Tests in Docker Container
        run: docker run docker-python-app